let lastGeneratedPdf=null;
async function assetToDataUrl(path){const url=new URL(path,document.baseURI).href;const response=await fetch(url);if(!response.ok)throw new Error(`Falha ao carregar ${path}`);const blob=await response.blob();return await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(blob);});}
function pdfStatusKind(v){const s=String(v||'').toLowerCase();if(['ok','normal','bom','excelente','presente','não','nao'].includes(s))return'good';if(['avaria','problema','anormal','ruim','sim','ausente','acesa'].includes(s))return'bad';if(['regular','atenção','atencao'].includes(s))return'warn';return'neutral';}
function brDate(iso){try{return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short'}).format(new Date(iso));}catch{return'-';}}
async function generateEvaluationPDF(record){
 if(!window.jspdf?.jsPDF)throw new Error('Biblioteca de PDF indisponível.');
 const {jsPDF}=window.jspdf;const doc=new jsPDF({unit:'mm',format:'a4',compress:true});const W=210,H=297,M=14;const navy=[12,2,78],blue=[12,2,78],green=[22,128,60],red=[198,40,40],amber=[183,121,0],gray=[95,98,110];const data=record.data||{};let logoData=null;try{logoData=await assetToDataUrl('./assets/logo.png');}catch(e){console.warn(e);}let y=28;
 const addHeader=()=>{doc.setFillColor(...navy);doc.rect(0,0,W,22,'F');if(logoData){try{doc.setFillColor(255,255,255);doc.roundedRect(M,3,34,16,2,2,'F');doc.addImage(logoData,'PNG',M+1.5,4.5,31,13);}catch(e){}}doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(10.5);doc.text('RELATÓRIO DE AVALIAÇÃO DE VEÍCULO USADO',W-M,9,{align:'right'});doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text(`Data da avaliação: ${brDate(record.createdAt)}`,W-M,15,{align:'right'});doc.setTextColor(0,0,0);};
 const addFooter=(page,total)=>{doc.setDrawColor(210,214,226);doc.setLineWidth(.25);doc.line(M,H-14,W-M,H-14);doc.setFont('helvetica','normal');doc.setFontSize(7.3);doc.setTextColor(...gray);doc.text('Speed Multimarcas • Av. Antonio Marques Figueira, 149 • Suzano/SP • (11) 4747-8724',M,H-9);doc.text(`Página ${page} de ${total}`,W-M,H-9,{align:'right'});};
 const newPage=()=>{doc.addPage();addHeader();y=29;};const need=h=>{if(y+h>H-20)newPage();};
 const section=title=>{need(12);doc.setFillColor(...navy);doc.roundedRect(M,y,W-2*M,8,1.8,1.8,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text(title,M+3,y+5.2);doc.setTextColor(0,0,0);y+=11;};
 const pairGrid=rows=>{const colW=(W-2*M-8)/2,leftX=M,rightX=M+colW+8;for(let i=0;i<rows.length;i+=2){need(11);const draw=(row,x)=>{if(!row)return;doc.setFontSize(8);doc.setFont('helvetica','bold');doc.setTextColor(35,35,40);doc.text(`${row[0]}:`,x,y);doc.setFont('helvetica','normal');doc.setTextColor(25,25,30);doc.text(doc.splitTextToSize(String(row[1]||'-'),colW),x,y+4);doc.setDrawColor(...blue);doc.setLineWidth(.18);doc.line(x,y+7.5,x+colW,y+7.5);};draw(rows[i],leftX);draw(rows[i+1],rightX);y+=10;}};
 const checklistTwoColumns=(title,items)=>{section(title);const entries=Object.values(items||{});const mid=Math.ceil(entries.length/2),cols=[entries.slice(0,mid),entries.slice(mid)],gap=8,colW=(W-2*M-gap)/2,x1=M,x2=M+colW+gap,rows=Math.max(cols[0].length,cols[1].length);for(let r=0;r<rows;r++){need(13);const draw=(item,x)=>{if(!item)return;doc.setFontSize(7.5);doc.setFont('helvetica','bold');doc.setTextColor(30,30,35);doc.text(doc.splitTextToSize(item.label||'-',colW-24),x,y);const kind=pdfStatusKind(item.value);if(kind==='good')doc.setTextColor(...green);else if(kind==='bad')doc.setTextColor(...red);else if(kind==='warn')doc.setTextColor(...amber);else doc.setTextColor(...gray);doc.setFont('helvetica','bold');doc.text(String(item.value||'-'),x+colW,y,{align:'right'});if(item.note){doc.setFont('helvetica','normal');doc.setTextColor(...gray);doc.text(doc.splitTextToSize(item.note,colW),x,y+4);}doc.setDrawColor(...blue);doc.setLineWidth(.18);doc.line(x,y+8.5,x+colW,y+8.5);};draw(cols[0][r],x1);draw(cols[1][r],x2);y+=12;}y+=2;};
 addHeader();
 section('1. Vendedor / Cliente');pairGrid([['Nome do vendedor',data.sellerName],['Nome do cliente',data.clientName],['Celular do cliente',data.clientMobile],['Telefone fixo do cliente',data.clientPhone]]);
 section('2. Identificação do veículo');pairGrid([['Placa',data.plate],['Marca',data.brand],['Modelo',data.model],['Versão',data.version],['Ano fab./modelo',data.year],['Quilometragem',data.mileage?`${Number(data.mileage).toLocaleString('pt-BR')} km`:'-'],['Cor',data.color],['Câmbio',data.transmission],['Combustível',data.fuel]]);
 checklistTwoColumns('3. Lataria e pintura',record.checklist?.bodywork);checklistTwoColumns('4. Interior e equipamentos',record.checklist?.interior);checklistTwoColumns('5. Mecânica e pneus',record.checklist?.mechanical);
 section('7. Avaliação comercial');pairGrid([['Valor FIPE / referência',data.referenceValue],['Valor solicitado',data.requestedValue],['Funilaria / pintura',data.bodyworkCost],['Mecânica',data.mechanicalCost],['Pneus',data.tiresCost],['Outros custos',data.otherCost],['Custo total de preparação',data.totalCost],['Valor sugerido para compra',data.suggestedPurchaseValue]]);
 need(22);doc.setFont('helvetica','bold');doc.setFontSize(8);doc.setTextColor(35,35,40);doc.text('Classificação geral:',M,y);const rk=pdfStatusKind(data.overallRating);if(rk==='good')doc.setTextColor(...green);else if(rk==='bad')doc.setTextColor(...red);else if(rk==='warn')doc.setTextColor(...amber);else doc.setTextColor(...gray);doc.text(String(data.overallRating||'-'),M+42,y);doc.setDrawColor(...blue);doc.setLineWidth(.18);doc.line(M,y+3,W-M,y+3);y+=8;doc.setFont('helvetica','bold');doc.setTextColor(35,35,40);doc.text('Observações finais:',M,y);doc.setFont('helvetica','normal');doc.setTextColor(25,25,30);const notes=doc.splitTextToSize(String(data.finalNotes||'-'),W-2*M);doc.text(notes,M,y+4);const notesH=Math.max(10,notes.length*4+6);doc.setDrawColor(...blue);doc.setLineWidth(.18);doc.line(M,y+notesH-1,W-M,y+notesH-1);y+=notesH;
 const photos=[...(record.photos||[]).sort((a,b)=>(a.index??999)-(b.index??999)).map(p=>({...p,isExtra:false})),...(record.extraPhotos||[]).map(p=>({...p,isExtra:true}))];
 if(photos.length){for(let i=0;i<photos.length;i+=2){newPage();section('6. Fotos da vistoria');const slots=[photos[i],photos[i+1]],topY=y,imageW=W-2*M,imageH=88;for(let s=0;s<2;s++){const p=slots[s];if(!p)continue;const boxY=topY+s*122;doc.setFont('helvetica','bold');doc.setFontSize(8.5);doc.setTextColor(...navy);doc.text(p.isExtra?'Foto adicional':(p.label||'Foto'),M,boxY);try{doc.addImage(p.dataUrl,'JPEG',M,boxY+4,imageW,imageH,undefined,'FAST');}catch(e){doc.setDrawColor(220);doc.rect(M,boxY+4,imageW,imageH);doc.setTextColor(...gray);doc.setFont('helvetica','normal');doc.text('Não foi possível renderizar esta foto.',M+4,boxY+12);}if(p.isExtra){doc.setFont('helvetica','bold');doc.setFontSize(7.8);doc.setTextColor(...gray);doc.text('Apontamento:',M,boxY+98);doc.setFont('helvetica','normal');doc.setTextColor(30,30,35);doc.text(doc.splitTextToSize(String(p.note||'-'),imageW),M,boxY+102);}}}}else{section('6. Fotos da vistoria');doc.setFont('helvetica','normal');doc.setFontSize(8.5);doc.setTextColor(...gray);doc.text('Nenhuma foto registrada nesta vistoria.',M,y);}
 const total=doc.internal.getNumberOfPages();for(let p=1;p<=total;p++){doc.setPage(p);addFooter(p,total);}const sanitizePart=(value,fallback)=>{const text=String(value||fallback||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'_').replace(/^_+|_+$/g,'');return text||fallback||'nao_informado';};const years=String(data.year||'').match(/\d{4}/g),year=years?.length?years[years.length-1]:(data.year||'sem_ano'),filename=[sanitizePart(data.brand,'sem_marca'),sanitizePart(data.model,'sem_modelo'),sanitizePart(year,'sem_ano'),sanitizePart(data.color,'sem_cor')].join('_')+'.pdf',blob=doc.output('blob'),url=URL.createObjectURL(blob);if(lastGeneratedPdf?.url)URL.revokeObjectURL(lastGeneratedPdf.url);lastGeneratedPdf={blob,url,filename};return lastGeneratedPdf;
}
